# Use this file as a starting point for a new values file. It is the minimum required changes to the default
# values file for the deployment to reasonably work.

student-helx:
  ambassador:
    securityContext:
      # -- Set these options when deploying to openshift. Defaults seen here.
      # runAsUser: 8888
  appstore:
    django:
      APPSTORE_DJANGO_PASSWORD: "qf9i154x0j2x"
      EMAIL_HOST_PASSWORD: ""
    saml:
      ASSERTION_URL: https://helx-test.apps.renci.org
      ENTITY_ID: "https://helx-test.apps.renci.org/saml2_auth/acs/"
    gitea:
      host: helx-test-gitea.apps.renci.org

professor-helx:
  enabled: false
  ambassador:
    securityContext:
      # -- Set these options when deploying to openshift. Defaults seen here.
      # runAsUser: 8888
  appstore:
    django:
      APPSTORE_DJANGO_PASSWORD: "8dm19g0q4cmx"
      EMAIL_HOST_PASSWORD: ""
    saml:
      ASSERTION_URL: https://helx-test.apps.renci.org
      ENTITY_ID: "https://helx-test.apps.renci.org/saml2_auth/acs/"
    gitea:
      host: helx-test-gitea.apps.renci.org

gitea:
  gitea:
    admin:
      email: "tcheek@renci.org"
      password: "Stormlight94"
    config:
      server:
        DOMAIN: helx-test-gitea.apps.renci.org
        ROOT_URL: https://helx-test-gitea.apps.renci.org
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    className: null
    enabled: true
    hosts:
    - host: helx-test-gitea.apps.renci.org
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - helx-test-gitea.apps.renci.org
      secretName: helx-test-gitea.apps.renci.org-tls

gitea-assist:
  config:
    data:
      gitea-api-url: helx-test-gitea.apps.renci.org