{{- if and (.Release.IsInstall) (index .Values "grader-api" "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: grader-api-postgresql
data:
  password: {{ randAlphaNum 24 | b64enc }}
  postgres-password: {{ randAlphaNum 24 | b64enc }}
{{- end }}