{{- if and (.Release.IsInstall) (index .Values "student-helx" "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: student-appstore-postgresql
data:
  password: {{ randAlphaNum 24 | b64enc }}
  postgres-password: {{ randAlphaNum 24 | b64enc }}
{{- end }}