apiVersion: v1
kind: Secret
metadata:
  name: student-appstore-postgresql
data:
  {{- if .Release.IsInstall }}
  password: {{ randAlphaNum 50 | b64enc }}
  postgres_password: {{ randAlphaNum 50 | b64enc }}
  {{ else }}
  password: {{ index (lookup "v1" "Secret" .Release.Namespace ( include "student-helx.appstore.postgresql.auth.existingSecret" . )).data "password" }}
  postgres_password: {{ index (lookup "v1" "Secret" .Release.Namespace ( include "student-helx.appstore.postgresql.auth.existingSecret" . )).data "postgres_password" }}
  {{ end }}